INDIE-RO/INDIE-RO

Frontend/.babelrc.json, Frontend/.gitignore, Frontend/.prettierrc, Frontend/.storybook/main.ts, Frontend/.storybook/preview.tsx, Frontend/package.json, Frontend/pnpm-lock.yaml, Frontend/public/index.html, Frontend/public/mockServiceWorker.js, Frontend/src/App.tsx, Frontend/src/index.tsx, Frontend/src/mocks/browser.ts, Frontend/src/mocks/handlers.js, Frontend/tsconfig.json, Frontend/webpack.config.js
- close #1
프론트 개발 환경 세팅
msw 오류가 남.
이어서 해결할 예정
x
=> chore: 개발 환경 세팅

Frontend/.storybook/main.ts, Frontend/.storybook/preview.tsx, Frontend/package.json, Frontend/pnpm-lock.yaml, Frontend/src/App.tsx, Frontend/src/components/@common/Button/Button.stories.ts, Frontend/src/components/@common/Button/Button.tsx, Frontend/src/components/@common/Button/button.css, Frontend/src/index.tsx, Frontend/src/router/router.tsx, Frontend/tsconfig.json, Frontend/webpack.config.js
- close #5 
- 절대경로 설정
- msw 설정
- 리액트쿼리 설정
- 라우팅 설정
서비스 페이지, 스토리북 페이지에서 `msw enabled` 동작도 확인했습니다.
```tsx
const queryClient = new QueryClient({
defaultOptions: {
queries: {
retry: 0,
staleTime: 1000 * 60 * 5 /** @TODO 논의 후 값 변경 필요 */,
gcTime: 1000 * 60 * 5,
throwOnError: true,
},
},
queryCache: new QueryCache({
onError: () => {
alert('[Error] Something went wrong!');
},
}),
});
```
staleTime, gcTime 값 어떻게 할지 논의가 필요할 것 같습니다!
=> chore: 추가 초기세팅 및 스토리북 설정

Frontend/.storybook/preview-body.html, Frontend/package.json, Frontend/pnpm-lock.yaml, Frontend/src/App.tsx, Frontend/src/components/@common/Svg/SvgIcon.stories.tsx, Frontend/src/components/@common/Svg/SvgIcon.tsx, Frontend/src/components/@common/Svg/SvgSprite.tsx, Frontend/src/components/@common/index.ts, Frontend/src/index.tsx, Frontend/tsconfig.json, Frontend/webpack.config.js
- close #7 
아이콘 스프라이트를 설정하였습니다.
x
글로벌 스타일 설정 후 아이콘 색상 변경할 예정입니다.
=> 아이콘 스프라이트 설정

.github/labeler.yml
- close #14 
- YAML 파일 오류해결을 위해 탭 대신 공백문자로 수정했습니다!
=> chore: yml파일 탭 문자 공백문자로 변경

Frontend/src/styles/GlobalStyle.tsx, Frontend/src/styles/font.ts, Frontend/src/styles/theme.ts
- close #22
- 폰트 설정
- html 62.5 추가
- rem 단위 수정
설마설마 했는데 진짜로 프리텐다드 설정을 안했더라구요 😅
이제 진짜 폰트 끄읏-
x
x
=> refactor: 폰트 재설정

.github/ISSUE_TEMPLATE/REFACTOR.yml, .github/labeler.yml, .github/workflows/pr-auto-assign.yml
=> feat: refactor 이슈 템플릿 추가 및 리뷰어 등록 워크플로우 수정

Frontend/.storybook/preview-body.html, Frontend/src/components/@common/Svg/SvgIcon.tsx, Frontend/src/components/@common/Svg/SvgSprite.tsx, Frontend/src/components/@common/Tag/Tag.stories.tsx, Frontend/src/components/@common/Tag/Tag.tsx, Frontend/src/emotion.d.ts, Frontend/src/styles/theme.ts
- close #35 
태그를 구현하였습니다.
theme type을 설정하였습니다.
x
x
=> feat: 태그 구현

Frontend/src/components/@common/Chip/Chip.stories.tsx, Frontend/src/components/@common/Chip/Chip.tsx, Frontend/src/components/@common/ChipButton/ChipButton.stories.tsx, Frontend/src/components/@common/ChipButton/ChipButton.tsx, Frontend/src/components/@common/ChipInpput/ChipInput.stories.tsx, Frontend/src/components/@common/ChipInpput/ChipInput.tsx
- close #39 
Chip variant에 tag 디자인을 추가했고 standard 디자인 속성 중에 잘못 생각한 게 있어서 수정을 좀 했습니다! (width 같은거..)
-  [x] Chip에 tag 디자인 추가
x
x
=> feat: Chip 컴포넌트에 tag 디자인 추가

Frontend/src/components/@common/Dialog/Dialog.stories.tsx, Frontend/src/components/@common/Dialog/Dialog.tsx, Frontend/src/components/@common/Dialog/DialogContext.tsx, Frontend/src/components/@common/index.ts, Frontend/src/hooks/@common/index.ts, Frontend/src/hooks/@common/useContextInScope.ts, Frontend/src/utils/@common.ts
- close #46 
```tsx
// context 내부에서 사용하는 경우 value를 반환하고 외부에서 사용하는 경우 에러를 던짐
export const useDialogContext = () => useContextInScope(DialogContext);
```
- 컴파운드 패턴을 사용하여 `dialog`의 기능과 기본적인 디자인을 포함하는 **Dialog** 컴포넌트를 구현했습니다.
- **context api**를 사용하여 `openDialog`, `closeDialog` 등의 값들을 공유할 수 있도록 했습니다.
- `asChild` 속성을 이용하여 현재 컴포넌트의 속성 값을 자식 컴포넌트로 복사하여 자식 컴포넌트를 리턴할 수 있습니다.
- `location` 속성에 `center` 또는 `bottom`을 주어 dialog가 open되는 방식을 설정할 수 있습니다.
- `onBackdropClick`을 통해 백드롭 클릭 시 dialog 닫기(기본 동작) 후 추가적인 로직을 실행시킬 수 있습니다.(생략 시 닫는 기능만 실행)
- `Dialog.Close`에 `onClick`을 통해 백드롭 클릭 시 dialog 닫기(기본 동작) 후 추가적인 로직을 실행시킬 수 있습니다.(생략 시 닫는 기능만 실행)
사용방법은 아래와 같습니다.
```tsx
<Dialog
location={location}
onBackdropClick={() => console.log('Close Modal(default) & Do Something!')}
>
<Dialog.Trigger asChild>
<button …
```
=> feat: Dialog 컴포넌트 구현

.github/workflows/label.yml
- close #50
이슈 라벨링 자동화를 구현하였습니다.
x
x
=> feat: 이슈 라벨링 자동화 구현

.github/workflows/label.yml
- close #52 
라벨링 비동기로 변경했습니다.
x
x
=> refactor: 이슈 라벨링 비동기로 변경

.github/workflows/label.yml
=> refactor: uses 버전 변경

.github/workflows/issue-label.yml, .github/workflows/pr-label.yml
- close #56 
라벨링 한 파일을 분리하였습니다.
x
x
=> refactor: label 자동화 로직 분리

.github/workflows/pr-auto-assign.yml
- close #58 
- 리뷰어 등록 워크플로우 리뷰어 목록 수정
=> feat: 리뷰어 목록 수정

Frontend/src/components/@common/ProgressBar/ProgressBar.stories.tsx, Frontend/src/components/@common/ProgressBar/ProgressBar.tsx
- close #48 
프로그래스 바를 구현하였습니다.
x
x
=> feat: ProgressBar 구현

Backend/Indiero/src/main/java/com/indiero/controller/MetadataController.java, Backend/Indiero/src/main/java/com/indiero/domain/Metadata.java, Backend/Indiero/src/main/java/com/indiero/service/MetadataService.java
- close #64
메타데이터 조회 기능을 구현하였습니다.
x
x
=> feat: 메타데이터 조회 기능 구현

Frontend/.storybook/preview-body.html, Frontend/public/index.html, Frontend/src/App.tsx, Frontend/src/components/@common/Chip/Chip.tsx, Frontend/src/components/@common/Dialog/Dialog.tsx, Frontend/src/components/@common/Svg/SvgSprite.tsx, Frontend/src/components/@common/Toast/Toast.stories.tsx, Frontend/src/components/@common/Toast/Toast.tsx, Frontend/src/components/@common/Toast/ToastContext.tsx, Frontend/src/components/@common/Toast/useToastProvider.ts, Frontend/src/components/@common/index.ts, Frontend/src/emotion.d.ts, Frontend/src/styles/theme.ts
- close #62
Toast를 root 요소 외부에 렌더링하여 스타일링 등을 쉽게 관리할 수 있도록 `createPortal`을 사용했습니다. (`Toast` 목록을 id=`toast-container`인 dom 요소 내부에 렌더링)
전역에서 toast 생성 메소드(e.g. `toast.success('성공!')`)를 이용해 Toast를 생성할 수 있도록 `ContextAPI`를 사용하였습니다. 
```tsx
function Homepage() {
const { toast } = useToast();
const onClick = () => toast.success('Hi, there!');
return (
<section css={Container}>
<button type='button' style={{ color: 'white' }} onClick={onClick}>
Toast!
</button>
</section>
);
}
```
- `TOAST_NUM_LIMIT = 3`으로 주어 Toast 개수가 3을 초과했을 경우 0.5초 뒤 가장 오래된 Toast부터 삭제하도록 했습니다. 3개만 보여주는 건 넘 적을까요? 
- Toast 출력 시간은 4초로 설정했습니다! 혹시 너무 짧거나 길다고 생각된다면 말해주세용
=> feat: Toast 컴포넌트 구현

Backend/Indiero/src/main/java/com/indiero/service/MetadataService.java
- close #68
정책 정렬 메타데이터를 수정하였습니다.
x
x
=> refactor: 정책 정렬 메타데이터 수정

Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/domain/Policy.java, Backend/Indiero/src/main/java/com/indiero/dto/Description.java, Backend/Indiero/src/main/java/com/indiero/dto/OtherInfo.java, Backend/Indiero/src/main/java/com/indiero/dto/Qualification.java, Backend/Indiero/src/main/java/com/indiero/dto/Tag.java, Backend/Indiero/src/main/java/com/indiero/dto/response/DetailPolicyResponse.java, Backend/Indiero/src/main/java/com/indiero/repository/PolicyRepository.java, Backend/Indiero/src/main/java/com/indiero/service/MetadataService.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #66 
정책 상세 정보 조회 기능을 구현하였습니다.
x
x
=> 정책 상세 정보 조회 기능 구현

Frontend/src/components/@common/IndieroHeader/IndieroHeader.tsx, Frontend/src/components/@common/NavigableHeader/NavigableHeader.tsx, Frontend/src/components/@common/NavigationBar/NavigationBar.tsx
=> feat: 헤더, 네비게이션 바 사이즈 관련 스타일 변경

Backend/Indiero/src/main/java/com/indiero/common/WebBinderControllerAdvice.java, Backend/Indiero/src/main/java/com/indiero/controller/MetadataController.java, Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/dto/request/SearchPolicyParams.java, Backend/Indiero/src/main/java/com/indiero/dto/response/ListPolicyResponse.java, Backend/Indiero/src/main/java/com/indiero/repository/PolicyQueryRepository.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #81
키워드 검색 결과 조회 기능을 구현하였습니다.
x
x
=> feat: 키워드 검색 결과 조회 기능 구현

Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/dto/request/AllPolicyParams.java, Backend/Indiero/src/main/java/com/indiero/repository/PolicyRepository.java, Backend/Indiero/src/main/java/com/indiero/service/MetadataService.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #98 
모두보기 결과 조회 기능을 구현하였습니다.
x
x
=> feat: 모두보기 결과 조회 기능 구현

Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/domain/Word.java, Backend/Indiero/src/main/java/com/indiero/dto/response/WordCloudResponse.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #110 
워드클라우드 조회 기능을 구현하였습니다.
x
x
=> feat: 워드클라우드 조회 기능 구현

Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #115 
워드클라우드 단어 가중치를 변경하였습니다.
x
x
=> refactor: 워드클라우드 단어 가중치 변경

Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #117
정책 상세 정보 조회 기능을 수정하였습니다.
x
x
=> refactor: 정책 상세 정보 조회 기능 수정

Frontend/src/components/@common/Dialog/Dialog.tsx
- close #112 
다이얼로그의 백드롭 색상을 변경하였습니다.
기존 투명도 0.1에서 0.3으로 변경하였습니다.
x
x
=> refactor: 다이얼로그 백드롭 색상 변경

Frontend/src/pages/IntroPage.tsx
- close #121
- 인트로 페이지에 멘트를 추가하고, 디자인하였습니다.
x
x
=> feat: 인트로 페이지 멘트 구현

Frontend/src/components/Policy/CustomInfo/CustomInfo.hook.ts, Frontend/src/components/Policy/CustomInfo/CustomInfo.tsx, Frontend/src/pages/CustomInfoPage.tsx, Frontend/src/pages/IntroPage.tsx, Frontend/src/pages/NotFoundPage.tsx, Frontend/src/pages/SurveyPage/SurveyAgePage.tsx, Frontend/src/pages/SurveyPage/SurveyCategoryPage.tsx, Frontend/src/pages/SurveyPage/SurveyRegionPage.tsx
- close #130 
custom Info에 설문 관련 meta api가 useQuery로 수정됨에 따라 undefined 처리를 해주었습니다.
버튼의 position을 fixed로 변경하였습니다.
맞춤 정보가 없는 경우 스크롤이 생기며 들썩거리는 현상을 수정하였습니다.
x
x
=> refactor: 버튼 스타일 fixed로 변경

Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/domain/KeywordCount.java, Backend/Indiero/src/main/java/com/indiero/repository/KeywordRepository.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #123 ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ 
검색어 저장 기능을 구현하였습니다.
x
x
=> feat: 검색어 저장 기능 구현

.github/workflows/deploy.yml
- close #139 
배포 자동화 파일 작성하였습니다.
x
x
=> feat: 배포 자동화 파일 작성

.github/workflows/frontend-playwright.yml, .github/workflows/issue-label.yml, Frontend/src/constants/error.ts
- close #145 
- 이슈 할당자 자동 생성하는 로직을 구현하였습니다.
- 문의 이메일을 변경하였습니다.
x
x
=> feat: 이슈 할당자 자동 등록 구현

.github/workflows/frontend-deploy.yml
- close #150 
- 구글 애널리틱스 아이디 추가
x
x
=> fix: 구글 애널리틱스 아이디 추가

Frontend/src/constants/path.ts, Frontend/src/index.tsx, Frontend/src/mocks/handlers/metaDataHandlers.js, Frontend/src/mocks/handlers/policyHandlers.js, Frontend/src/mocks/handlers/surveyHandlers.js, Frontend/src/mocks/handlers/wordCloudHandlers.js, Frontend/src/types/env.d.ts
- close #152 
msw base url을 설정하였습니다.
x
x
=> feat: msw base url 설정

Backend/Indiero/build.gradle, Backend/Indiero/src/main/java/com/indiero/common/WebConfig.java, Backend/Indiero/src/main/java/com/indiero/controller/PolicyController.java, Backend/Indiero/src/main/java/com/indiero/domain/Policy.java, Backend/Indiero/src/main/java/com/indiero/dto/request/UserPolicyParams.java, Backend/Indiero/src/main/java/com/indiero/dto/response/RecommendationPolicyResponse.java, Backend/Indiero/src/main/java/com/indiero/repository/PolicyRepository.java, Backend/Indiero/src/main/java/com/indiero/service/MetadataService.java, Backend/Indiero/src/main/java/com/indiero/service/PolicyService.java
- close #167
AI 추천 정책 조회 기능을 구현하였습니다.
x
x
=> feat: AI 추천 정책 조회 기능

.github/release-drafter.yml, .github/workflows/release.yml, Frontend/src/components/Policy/RecommendedPolicy/RecommendedPolicy.query.ts
=> chore: 릴리즈 워크플로우 생성

Frontend/src/components/Policy/RecommendedPolicy/RecommendedPolicy.query.ts, Frontend/src/components/Policy/RecommendedPolicy/RecommendedPolicy.tsx
- close #176 
- 사이즈별로 글자 크기 및 위치를 수정하였습니다.
x
x
=> refactor: 사이즈 별 글자 크기 수정
